import request from './request';

const logColor = '#EF476F';

const owner = 'inkblotty';
const repo = 'lizard-buddy';
const baseBranch = 'main';

const nowDate = new Date();
const now = `${nowDate.getFullYear()}-${nowDate.getMonth() + 1}-${nowDate.getDate()} at ${nowDate.getUTCHours()}:${nowDate.getUTCMinutes()} UTC`;
const backupTitle = `Generated Lizard Buddy PR`;
const backupBody = `Generated by Lizard Buddy Manual Test at ${now}`;

interface PROptions {
  /**
   * Title of your PR
   */
  title?: string;
  /**
   * Describe your PR
   */
  body?: string;
  /**
   * The branch name you're submitting a PR from
   */
  head: string;
}
const createPullRequest = async (options: PROptions): Promise<any> => {
  const { title = backupTitle, body = backupBody, head } = options;
  try {
    const fullBody = !body?.includes(now) ? `${body}\n\n${now}` : body;
    console.log('%c\nSubmitting your PR to lizard-buddy repo...', `color: ${logColor}`)
    const response = await request(
      `POST /repos/{owner}/{repo}/pulls`, { owner, repo, title, body: fullBody, head, base: baseBranch }
    );
    console.log(`%c\nSuccessfully submitted PR for ${head}! Go check out github.com/inkblotty/lizard-buddy/pulls.`, `color: ${logColor}`);
    return response;
  } catch (err) {
    console.log(`%c Failed to create PR for ${head}`, `color: ${logColor}`, err);
    throw err;
  }
}
export default createPullRequest;
