name: Typecheck

on:
  pull_request:
    branches:
      - main

jobs:
  typechecktheme:
    runs-on: ubuntu-latest
    name: typechecktheme
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        run: yarn install
      - name: Typecheck Theme
        run: cd theme && yarn compile

  typecheckserver:
    runs-on: ubuntu-latest
    name: typecheckserver
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        run: yarn install
      - name: Typecheck Server
        run: cd server && yarn compile

  typecheckgui:
    runs-on: ubuntu-latest
    name: typecheckgui
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        run: yarn install
      - name: Typecheck Gui
        run: cd gui && yarn build
